### PR TITLE
DirectionalType "LANTERN" created

### PR DESCRIPTION
**Pull request by Rexblane**
I just created a simple "lantern" DirectionalType to make only up and down variations

### CODE REVIEW

**Comment by Boy0000** [comment]
Not sure on the usecase for this. I would assume this is for using with models, like the vanilla lanterns meaning the block needs to be transparent. Which no oraxen noteblock would support, not against this just not sure on the usecase

**Comment by oliviathevampire** [comment]
Would allow for hanging blocks

**Comment by Boy0000** [comment]
It means u can have a block have a different texture when placed underneath another yes
But lanterns arent blocks, theyre models. I only see a real benefit to this if it could be that or atleast transparency was a thing
Not against it but feels like just a similar thing to "SIDEWAYS Mechanic, different block when placed on blockface EAST"
Log, dropper and furnace serve similar functionality to already existing directional MC vanilla blocks

For this i would atleast think it would mean we had a lamp/lantern mechanic for blocks.
Though RN LightAPI is broken so

**Comment by Tub-Net** [comment]
I agree, this would be amazing

**Pull request closed without merging**
