### PR TITLE
Add common spell mechanic & fireball spell

### PR DESCRIPTION
**Pull request by MrYoup**
The spell mechanic apply as parent of energybeam, witherskull, thor and fireball.
This mechanic handles configuration for Timing and MaxCharges.

Max charges is added without altering previous versions of mechanics. If absent from items configuration file then infinite amount of charges is taken into account, not altering already existing mechanics.

If charges is specified:
-1 makes spell have infinite charges
X charges makes item usable X times before it disappear. Additionnal Lore is insertet at the begining to show how many charges are left on the item.

Fireball is a very simple fireball spell spawning a fireball travelling in the pointed direction at launch.
The speed and radius is configurable in addition to timing and charges provided by the spell class.

Hope you like it that way :)

### CODE REVIEW

**Review by Th0rgal — APPROVED** [review]
It looks good to me!

**Comment by Th0rgal** [comment]
Great job man, I'll release it tonight!

**Comment by MrYoup** [comment]
Nice, Thanks for the merge ! 
I will probably add some more spells such as Healing, poison, ... 
I will always try to add things without breaking anything else :)

Very nice job on a well developped plugin ;)

**Comment by Th0rgal** [comment]
Thanks man, I appreciate that!

**Pull request merged**
