### PR TITLE
Folia

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by oliviathevampire** [comment]
You're not checking if it tries to set into a slot that is higher than 53, or technically it should be 45, so you need to check if the items tries to get into a slot that is higher than 45 and if so, add them to the next page. This is technically why addItem is better as it automatically makes it create a new page if it's over 45 items

**Comment by Boy0000** [comment]
Not an issue as thriumph has pagesoze set to 45 so everything after auto filters into further pages

**Comment by oliviathevampire** [comment]
Nope, I have tested this myself with the same code and the configs from my server, and it tries to set items in slot even over 53, that is part of the auto-placed ones, the ones I manually have set works, but those that are automatically set tries to continue.

**Comment by Boy0000** [comment]
If you mean in the mainGui then sure that might be the case here, but subguis should not. Feel free to open a PR with a quick fix. Otherwise ill do it tomorrow or when i have time

**Comment by oliviathevampire** [comment]
> If you mean in the mainGui then sure that might be the case here, but subguis should not. Feel free to open a PR with a quick fix. Otherwise ill do it tomorrow or when i have time

ye I meant the mainGui, not really sure the best way to do it tho

**Comment by oliviathevampire** [comment]
You need to fix the opposite icons for the buttons :D you have arrow if the item is loaded and the item if it's not :D for the next and previous and also the exit :D

**Pull request merged**
