### PR TITLE
Add support for Shapeless and Furnace Recipes, add Furnace Recipe Builder.

### PR DESCRIPTION
**Pull request by yzl210**
Add support for Shapeless and Furnace Recipes, add Furnace Recipe Builder.

### CODE REVIEW

**Comment by Th0rgal** [comment]
Thank you very much for the Pull Request! I'm currently not at home but I'll try it asap. I'll also add you to the contributors.md file

**Comment by yzl210** [comment]
Thanks

**Comment by yzl210** [comment]
And one thing, I forgot to remove the debug section in FurnaceBuilder, line 51 and 52, you can remove it.

**Comment by Th0rgal** [comment]
> And one thing, I forgot to remove the debug section in FurnaceBuilder, line 51 and 52, you can remove it.

Alright, I'll do it!

**Comment by Th0rgal** [comment]
> And one thing, I forgot to remove the debug section in FurnaceBuilder, line 51 and 52, you can remove it.

Hmm I'm unable to find it. Are you sure you didn't already remove it?

**Pull request merged**
