### PR TITLE
More farming mechanics

### PR DESCRIPTION
**Pull request by Boy0000**
Adds a "Farm Block" block. Essentially farmland for custom blocks, but will eventually have more interactions.
Includes mechanic for watering can aswell, tho I plan on merging all this into a Farming mechanic by the end of the PR.

Not sure on how it should split the "isFarmBlock" mechanic as they do kinda only exist for noteblocks, tho they could in theory be furniture aswell. thoughts?
First mechanic i add so it probably is badly formatted so please correct anything.

### CODE REVIEW

**Comment by Boy0000** [comment]
Currently implements the dryout effect similar to farmland in vanilla
Also adds the watercan, tho it is still single use.

Dryout does currently not take into account surrouding waterblocks

**Comment by oliviathevampire** [comment]
I'm hyped for this! thanks for making this!

**Review by oliviathevampire — DISMISSED** [review]

**Comment by Boy0000** [comment]
Still not fully finished. Some bugs and additions needed to watercans. I'll re-request a review when I've had time to finalize this 👍

**Comment by Boy0000** [comment]
Water from flowing water. Other blocks check for whet farmland/farmblocks as well as water

https://user-images.githubusercontent.com/62521371/165863759-90c51a78-39c7-4705-a8f8-e11a7a459bba.mp4


Watercan made to be used on farmblocks if watersources not available

https://user-images.githubusercontent.com/62521371/165863818-0681af4d-8da3-431e-8b9c-ab150a1c8b64.mp4


Gropgrowth on farmblocks, fixes issue with blocks growing past final stage
https://user-images.githubusercontent.com/62521371/165863847-f5df029a-1c75-4142-98b2-c381f85d940d.mp4

**Review by Th0rgal — APPROVED** [review]
lgtm

**Pull request merged**
