### PR TITLE
2.0

### PR DESCRIPTION
**Pull request by Boy0000**
### TODO
Mechanics
-----
- [ ] Convert FurnitureSeats to use packets

**[[General]()]**
-----
- Change CustomSound handling
  * `sound.yml` -> `sounds.yml`
  * Allow for all optional-properties specified on the [wiki](https://minecraft.fandom.com/wiki/Sounds.json#File_structure)
  * Refactor to allow for custom namespaces
- Multi-font Glyphs

**[[ResourcePack]()]**
-----
- Entirely new pack-structure to improve importing external packs
  * A detailed explanation can be found [here]()
- ResourcePack is now sent before player loads in the server (Configuration Phase)
- Automatic ModelEngine-pack Import
- New PackServer options
  * POLYMATH - same as in 1.x
  * SELFHOST - SelfHost/Localhost the pack on your server itself
- Improve pack-merging and conflict handling
- Default Assets are now included in a external pack instead of in the Jar itself
- Built-in Pack-Obfuscator

**[[Furniture]()]**
-----
- Packet-based Furniture & Furniture Hitboxes
  * **IMPORTANT:** Contains breaking changes from 1.0, [read this before updating]()
  * Aims to fix tons of issues with existing furniture leaving behind hitboxes & not updating properly
- Support for multiple interaction-hitboxes
- Seat-mechanic is no longer bound to barrierHitbox
  * Meaning you can define as many seats as you want at whatever position you want

**[[Custom Blocks]()]**
-----
- NoteBlock & StringBlock mechanics moved under new common `CustomBlock-Mechanic`
- NoteBlock-mechanic custom_variation limit 749 -> 1149
  * **IMPORTANT:** Contains breaking changes from 1.0, [read this before updating]()
- NoteBlock-mechanic can now be used in beacons
- NoteBlock-mechanic can now be used without disabling vanilla noteblock functionality
  * Disabled by default in mechanics.yml
- Remade Custom-Block Breaking System
  * Closer to vanilla logic with tool-speed modifiers
  * Fixes bunch of minor bugs with breaking & sound from 1.X
- StringBlocks can now be placed ontop of water similar to Lilypads with `placeable_on_water`

**[[Custom Armor]()]**
-----
- SHADER CustomArmor is no longer supported as TRIMS work on all supported versions
  * If you still for some reason want to use SHADER method, you can use it by manually handling ResourcePackFiles
  * Follow the README here for [FancyPants](https://github.com/Ancientkingg/fancyPants) or the more optimized [LessFancyPants](https://github.com/Godlander/lessfancypants)

**[Removed]**
-----
- Dropped support for 1.20.3 & below
- Block-Mechanic (Mushroom Blocks), BedrockBreak-, Watering- & Farmblock-Mechanic have been removed
- BossShopPro compatibility

**[[Developer API]()]**
-----
The API has naturally had tons of breaking changes and new additions.
A detailed changelog can be found [here]()

### CODE REVIEW

**Comment by oliviathevampire** [comment]
How useable is 2.0 right now? is it that many bugs? how much of old configs for blocks will break?

**Comment by Boy0000** [comment]
> How useable is 2.0 right now? is it that many bugs? how much of old configs for blocks will break?

everything breaks, discord has devbuilds outside of that dont use 2.0 until it is released

**Comment by oliviathevampire** [comment]
> > How useable is 2.0 right now? is it that many bugs? how much of old configs for blocks will break?
> 
> everything breaks, discord has devbuilds outside of that dont use 2.0 until it is released

A bit difficult to get them when I can't join the discord

**Comment by Boy0000** [comment]
probably a valid reason for that
until 2.0 is released it isnt something ill consider stable to use on production
use at your own risk

**Comment by oliviathevampire** [comment]
Is all the links explaining the new stuff supposed to lead back to this PR?

**Comment by Boy0000** [comment]
> Is all the links explaining the new stuff supposed to lead back to this PR?

theyre not linked cuz the 2.0 update isnt released thus no updated docs for it yes

**Comment by oliviathevampire** [comment]
When 2.0 releases will there be an upgrading thing? to upgrade all the content to the new format

**Comment by oliviathevampire** [comment]
How "stable" is this right now?

**Pull request closed without merging**
