### PR TITLE
Add more recipe loaders

### PR DESCRIPTION
**Pull request by CrazyDev05**
This PR aims to add every recipe type besides brewing

### CODE REVIEW

**Review by Boy0000 — CHANGES_REQUESTED** [review]
Needs to add commands and visual versions of all these loaders

**Comment by CrazyDev05** [comment]
now i only need to add the stonecutter, but i will do that tomorrow

**Comment by CrazyDev05** [comment]
the recipe builders and commands are implemented

**Comment by Boy0000** [comment]
merged into #840 thanks

**Pull request closed without merging**
