### PR TITLE
Add OraxenPackCreateEvent

### PR DESCRIPTION
**Pull request by Euphillya**
This adds an event when the texture pack is ready. This is useful if you use an external resource pack generator that does a merge (like ResourcePackManager)

### CODE REVIEW

**Comment by Boy0000** [comment]
this event is pointless as OraxenPackGeneratedEvent is called right before and does what this does?

**Comment by Euphillya** [comment]
> this event is pointless as OraxenPackGeneratedEvent is called right before and does what this does?

No, he is called before.

**Comment by Boy0000** [comment]
Oraxens event is called first, then ur just calling this new event, there is no difference here as i see anything other than the name of the event

image

**Comment by Boy0000** [comment]
there is no reason to do anythign after pack.zip is made
The event oraxen calls now if meant for plugins to tweak the RP before its finished
your event here does nothing important other than say "pack is now zipped" which is not relevant
its a pointless middle-event between OraxenPackGeneratedEvent and OraxenPackUploadedEvent

not gonna merge this one

**Comment by Euphillya** [comment]
> there is no reason to do anythign after pack.zip is made The event oraxen calls now if meant for plugins to tweak the RP before its finished your event here does nothing important other than say "pack is now zipped" which is not relevant its a pointless middle-event between OraxenPackGeneratedEvent and OraxenPackUploadedEvent
> 
> not gonna merge this one

Yeah, well it's useless. I'm sorry to tell you, but since the change of lead developer, I feel like it's getting worse than better.

**Pull request closed without merging**
