### PR TITLE
Breaker System Rework

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by Bruhhhh10** [comment]
Instead of making a list of tools and checking for all those cases, you could use and edit NMS getDestroyProgress method and edit the iblockdata.getDestroySpeed method to get rid of the mining fatigue check I'm pretty sure

**Comment by iqtesterr** [comment]
One thing to notice, in 24W06A Mojang added a new attribute to control the player break speed.
image

**Comment by bkgktp** [comment]
```
package gg.bckd00r.community.customblock.breaker;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.ProtocolManager;
import com.comphenix.protocol.events.ListenerPriority;
import com.comphenix.protocol.events.PacketAdapter;
import com.comphenix.protocol.events.PacketContainer;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.reflect.StructureModifier;
import com.comphenix.protocol.wrappers.BlockPosition;
import com.comphenix.protocol.wrappers.EnumWrappers;
import gg.bckd00r.community.customblock.CustomBlock;
import gg.bckd00r.community.customblock.mechanic.AdvancedBlockData;
import gg.bckd00r.community.customblock.mechanic.CustomBlockManager;
import gg.bckd00r.community.customblock.utils.destroy.Destroy;
import gg.bckd00r.community.customblock.utils.drops.Drop;
import gg.bckd00r.community.customblock.utils.packets.Packet;
import gg.bckd00r.community.customblock.utils.sounds.AdvancedSoundData;
import io.th0rgal.oraxen.api.OraxenBlocks;
import io.th0rgal.oraxen.api.OraxenFurniture;
import io.th0rgal.oraxen.api.events.furniture.OraxenFurnitureDamageEvent;
import io.th0rgal.oraxen.api.events.noteblock.OraxenNoteBlockDamageEvent;
import io.th0rgal.oraxen.api.events.stringblock.OraxenStringBlockDamageEvent;
import io.th0rgal.oraxen.mechanics.provided.gameplay.furniture.FurnitureMechanic;
import io.th0rgal.oraxen.mechanics.provided.gameplay.noteblock.NoteBlockMechanic;
import io.th0rgal.oraxen.mechanics.provided.gameplay.stringblock.StringBlockMechanic;
import io.th0rgal.protectionlib.ProtectionLib;
import org.bukkit.*;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;
import org.bukkit.event.block.Action;
import org.bukkit.event.block.BlockBreakEvent;
import org.bukkit.event.player.PlayerInteractEvent;
import org.bukkit.event.player.PlayerItemDamageEvent;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;
import org.bukkit.metadata.FixedMetadataValue;
import org.bukkit.plugin.java.JavaPlugin;
import org.bukkit.potion.PotionEffectType;
import org.bukkit.scheduler.BukkitScheduler;
import org.bukkit.scheduler.BukkitTask;
import org.bukkit.scoreboard.Team;

import java.util.*;

import static gg.bckd00r.community.customblock.mechanic.CustomBlockManager.getAdvancedBlockData;


public class BreakerSystem {

    private final Map<UUID, Location> BLOCK_DIG = new HashMap<>();
    private final Map<Location, BukkitTask> breakerPlaySound = new HashMap<>();
    private final ProtocolManager protocolManager;
    private final JavaPlugin instance;

    public BreakerSystem(JavaPlugin plugin) {
        instance = plugin;
        this.protocolManager = CustomBlock.protocol();
        //SLOW_DIGGING = new PotionEffect(PotionEffectType.SLOW_DIGGING, PotionEffect.INFINITE_DURATION, Integer.MAX_VALUE, false, false, false);

    }

    public void registerListener() {
        protocolManager.addPacketListener(blockDamageListener);
    }


    private final PacketAdapter entityStatusPacket = new PacketAdapter(CustomBlock.get(),
            ListenerPriority.HIGHEST,
            PacketType.Play.Client.BLOCK_DIG) {

        @Override
        public void onPacketSending(PacketEvent event) {
            if (event.getPacketType() == PacketType.Play.Client.BLOCK_DIG) {
                //int entityId = event.getPacket().getIntegers().read(0);
                //byte status = event.getPacket().getBytes().read(0);

                // entityId ve status ile işlemler yapabilirsiniz.
                Bukkit.broadcastMessage("use item sending");
                //event.setCancelled(true);
            }
        }

        @Override
        public void onPacketReceiving(PacketEvent event) {
            if (event.getPacketType() == PacketType.Play.Client.BLOCK_DIG) {
                //int entityId = event.getPacket().getIntegers().read(0);
                //byte status = event.getPacket().getBytes().read(0);
                Bukkit.broadcastMessage("use item receiving");
                //event.setCancelled(true);

                // entityId ve status ile işlemler yapabilirsiniz.
                //Bukkit.broadcastMessage("receiving Entity #" + entityId + " Status: " + status);
            }
        }
    };


    private final String PLAYER_BREAK_TICK = "PLAYER_BREAK_TICK";

    private final PacketAdapter blockDamageListener = new PacketAdapter(CustomBlock.get(),
            ListenerPriority.HIGHEST,
            PacketType.Play.Client.BLOCK_DIG) {

        public void onPacketReceiving(PacketEvent event) {
            EnumWrappers.PlayerDigType type;
            PacketContainer packet = event.getPacket();
            final Player player = event.getPlayer();
            final ItemStack item = player.getInventory().getItemInMainHand();
            if (player.getGameMode() == GameMode.CREATIVE)
                return;

            StructureModifier<BlockPosition> dataTemp = packet.getBlockPositionModifier();
            StructureModifier<EnumWrappers.Direction> dataDirection = packet.getDirections();
            StructureModifier<EnumWrappers.PlayerDigType> data = packet.getEnumModifier(EnumWrappers.PlayerDigType.class, 2);

            try {
                type = data.getValues().get(0);
            } catch (IllegalArgumentException exception) {
                type = EnumWrappers.PlayerDigType.SWAP_HELD_ITEMS;
            }

            BlockPosition pos = dataTemp.getValues().get(0);
            final World world = player.getWorld();
            final Block block = world.getBlockAt(pos.getX(), pos.getY(), pos.getZ());

            BlockFace blockFace = (dataDirection.size() > 0) ? BlockFace.valueOf(dataDirection.read(0).name()) : BlockFace.UP;
            final Location location = block.getLocation();

            if (type == EnumWrappers.PlayerDigType.START_DESTROY_BLOCK) {
                Bukkit.getScheduler().runTask(instance, () -> {
                    if (CustomBlockManager.isCustomBlock(block) || block.getBlockData().getSoundGroup().getHitSound() == Sound.BLOCK_WOOD_HIT) {
                        BukkitTask task = Bukkit.getScheduler().runTaskTimer(CustomBlock.get(), () -> AdvancedSoundData.playHitSound(block), 2L, 4L);
                        breakerPlaySound.put(location, task);
                    }
                    setPlayerBreakTick(player, Bukkit.getCurrentTick());
                });

                AdvancedBlockData advancedBlockData = CustomBlockManager.getAdvancedBlockData(CustomBlockManager.getBlockId(block));
                if (!CustomBlockManager.isCustomBlock(block)) {
                    Bukkit.getScheduler().runTask(instance, () -> {
                        if (!(advancedBlockData != null && advancedBlockData.hasHardness())) {

                            //-1 ise setUpdatePotion'u çalıştırma
                            setPlayerBreakTick(player, -1);
                            Packet.removeMiningFatigue(player);
                        }
                    });
                    return;
                } else if (!(advancedBlockData != null && advancedBlockData.hasHardness())) {
                    Bukkit.getScheduler().runTask(instance, () -> {

                        //-1 ise setUpdatePotion'u çalıştırma
                        setPlayerBreakTick(player, -1);
                        Packet.removeMiningFatigue(player);
                    });
                }

                if (!(advancedBlockData != null && advancedBlockData.hasHardness()))
                    return;

                event.setCancelled(true);
                Bukkit.getScheduler().runTask(instance, () -> {
                    if (advancedBlockData.hasHardness())
                        Packet.sendMiningFatigue(player);
                });

                final PlayerInteractEvent playerInteractEvent =
                        new PlayerInteractEvent(player, Action.LEFT_CLICK_BLOCK, player.getInventory().getItemInMainHand(), block, blockFace, EquipmentSlot.HAND);
                Bukkit.getScheduler().runTask(instance, () -> Bukkit.getPluginManager().callEvent(playerInteractEvent));

                if (blockDamageEventCancelled(block, player))
                    return;

                BLOCK_DIG.put(player.getUniqueId(), location);
            } else {
                removeBlockMeta(player);
                Bukkit.getScheduler().runTask(instance, () -> {
                    if (breakerPlaySound.containsKey(location)) {
                        breakerPlaySound.get(location).cancel();
                        breakerPlaySound.remove(location);
                    }
                    //removeBlockMeta(player);
                    if (CustomBlockManager.isCustomBlock(block)) {
                        if (!ProtectionLib.canBreak(player, block.getLocation()))
                            player.sendBlockChange(block.getLocation(), block.getBlockData());
                        for (Entity entity : world.getNearbyEntities(location, 16.0D, 16.0D, 16.0D)) {
                            if (entity instanceof Player viewer) {
                                sendBlockBreak(viewer, location, 10);
                            }
                        }
                    }
                });
            }
        }
    };

    private void setUpdatePlayerPotionEffect(Player player) {
        int currentTick = Bukkit.getCurrentTick();
        int startingDamageTick = player.hasMetadata(PLAYER_BREAK_TICK) ? player.getMetadata(PLAYER_BREAK_TICK).get(0).asInt() : -1;
        if ((Math.floorMod(currentTick, 21) == 0)) {
            if (startingDamageTick != -1) {
                if (!isPlayerBreakBlock(player)) {
                    if (!Packet.hasMiningFatigueMeta(player)) {
                        Packet.sendMiningFatigue(player);
                    }
                }
            }
        }
    }

    public float getPlayerBreakTick(Player player) {
        return player.hasMetadata(PLAYER_BREAK_TICK) ? player.getMetadata(PLAYER_BREAK_TICK).get(0).asFloat() : 0;
    }

    public void setPlayerBreakTick(Player player, float tick) {
        player.setMetadata(PLAYER_BREAK_TICK, new FixedMetadataValue(instance, tick));
    }

    private float getPlayerStartingBreakTick(Player player) {
        return (Bukkit.getCurrentTick() - getPlayerBreakTick(player));
    }

    public void startBreakerTask() {
        BukkitScheduler scheduler = Bukkit.getScheduler();
        scheduler.runTaskTimer(instance, bukkitTask -> {
            Bukkit.getOnlinePlayers().forEach(player -> {
                setUpdatePlayerPotionEffect(player);

                if (!isPlayerBreakBlock(player))
                    return;

                Location location = BLOCK_DIG.getOrDefault(player.getUniqueId(), player.getLocation());
                final Block block = location.getBlock();
                float tick = getPlayerStartingBreakTick(player);

                final FurnitureMechanic furnitureMechanic = OraxenFurniture.getFurnitureMechanic(block);
                final Entity furnitureBaseEntity = furnitureMechanic != null ? furnitureMechanic.getBaseEntity(block) : null;
                final List<Location> furnitureBarrierLocations = furnitureMechanic != null && furnitureBaseEntity != null ? furnitureMechanic.getLocations(FurnitureMechanic.getFurnitureYaw(furnitureBaseEntity), furnitureBaseEntity.getLocation(), furnitureMechanic.getBarriers()) : Collections.singletonList(block.getLocation());

                /*
                if ((Math.floorMod((int) tick, 5) == 0)) {
                    if (!player.isOnGround()) {
                        player.setMetadata("JUMP", new FixedMetadataValue(instance, true));
                    } else player.setMetadata("JUMP", new FixedMetadataValue(instance, false));
                } //else player.setMetadata("JUMP", new FixedMetadataValue(instance, false));
                 */

                long blockBreakingTick;
                blockBreakingTick = calculateTickPeriod(player, location.getBlock(), player.getInventory().getItemInMainHand());
                if (/*isPlayerKeepsJumping(player) || */!player.isOnGround() || player.isFlying())
                    setPlayerBreakTick(player, ((getPlayerBreakTick(player) + 0.8f)));

                if (((player.isInWater() || player.isUnderWater()) && !player.getInventory().getItemInMainHand().containsEnchantment(Enchantment.WATER_WORKER)))
                    setPlayerBreakTick(player, ((getPlayerBreakTick(player) + 0.8f)));

                float adder = (9 / ((float) blockBreakingTick));
                int multiplierIndex = (int) Math.floor((adder * tick));


                //sendBlockBreak(player, location, multiplier);
                for (final Entity entity : location.getWorld().getNearbyEntities(location, 16, 16, 16)) {
                    if (entity instanceof Player viewer) {
                        if (furnitureMechanic != null) {
                            for (Location barrierLoc : furnitureBarrierLocations)
                                sendBlockBreak(viewer, barrierLoc, multiplierIndex);
                        } else sendBlockBreak(viewer, location, multiplierIndex);
                    }
                }
                if ((blockBreakingTick >= tick))
                    return;

                sendBlockBreak(player, location, 10);
                final BlockBreakEvent blockBreakEvent = new BlockBreakEvent(block, player);
                if (blockBreakEvent.isCancelled())
                    return;

                if (!blockBreakEvent.isCancelled() && ProtectionLib.canBreak(player, block.getLocation())) {
                    Bukkit.getServer().getPluginManager().callEvent(blockBreakEvent);
                    //CustomBlockManager.breakBlock(block, player);

                    PlayerItemDamageEvent playerItemDamageEvent = new PlayerItemDamageEvent(player, player.getInventory().getItemInMainHand(), 1);
                    Bukkit.getPluginManager().callEvent(playerItemDamageEvent);
                }
                removeBlockMeta(player);
            });
        }, 1L, 1L);

    }

    private boolean isPlayerKeepsJumping(Player player) {
        return player.getMetadata("JUMP").get(0).asBoolean();
    }

    private void removeBlockMeta(Player player) {
        Location location = BLOCK_DIG.getOrDefault(player.getUniqueId(), player.getLocation());
        if (breakerPlaySound.containsKey(location)) {
            breakerPlaySound.get(location).cancel();
            breakerPlaySound.remove(location);
        }
        setPlayerBreakTick(player, 0);
        BLOCK_DIG.remove(player.getUniqueId());
    }

    private boolean isPlayerBreakBlock(Player player) {
        return BLOCK_DIG.containsKey(player.getUniqueId());
    }

    private boolean isBlockBreaking(Location location) {
        return BLOCK_DIG.containsValue(location);
    }

    private void sendBlockBreak(Player player, Location location, int stage) {
        //Block block = location.getBlock();
        PacketContainer packet = this.protocolManager.createPacket(PacketType.Play.Server.BLOCK_BREAK_ANIMATION);
        packet.getIntegers().write(0, Integer.valueOf(location.hashCode())).write(1, Integer.valueOf(stage));
        packet.getBlockPositionModifier().write(0, new BlockPosition(location.toVector()));
        //BlockPosition.getConverter().getSpecific(location.toVector());
        /*
        if (!this.breakerPlaySound.contains(block)) {
            this.breakerPlaySound.add(block);
            BlockSounds blockSounds = getBlockSounds(block);
            if (blockSounds != null && blockSounds.hasHitSound())
                Bukkit.getScheduler().runTask(instance, () -> BlockHelpers.playCustomBlockSound(block.getLocation(), getSound(block), blockSounds.getHitVolume(), blockSounds.getHitPitch()));
            Bukkit.getScheduler().runTaskLater(instance, () -> this.breakerPlaySound.remove(block), 3L);
        }
         */
        protocolManager.sendServerPacket(player, packet);
    }

    private boolean blockDamageEventCancelled(Block block, Player player) {
        Material type = block.getType();
        if (type == Material.NOTE_BLOCK) {
            NoteBlockMechanic mechanic = OraxenBlocks.getNoteBlockMechanic(block);
            if (mechanic == null) return true;
            OraxenNoteBlockDamageEvent event = new OraxenNoteBlockDamageEvent(mechanic, block, player);
            Bukkit.getScheduler().runTask(instance, () -> {
                Bukkit.getPluginManager().callEvent(event);
            });
            return event.isCancelled();
        } else if (type == Material.TRIPWIRE) {
            StringBlockMechanic mechanic = OraxenBlocks.getStringMechanic(block);
            if (mechanic == null) return true;
            OraxenStringBlockDamageEvent event = new OraxenStringBlockDamageEvent(mechanic, block, player);
            Bukkit.getScheduler().runTask(instance, () -> {
                Bukkit.getPluginManager().callEvent(event);
            });
            return event.isCancelled();
        } else if (type == Material.BARRIER) {
            try {
                return Bukkit.getScheduler().callSyncMethod(instance, () -> {
                    FurnitureMechanic mechanic = OraxenFurniture.getFurnitureMechanic(block);
                    if (mechanic == null) return true;
                    Entity baseEntity = mechanic.getBaseEntity(block);
                    if (baseEntity == null) return true;
                    OraxenFurnitureDamageEvent event = new OraxenFurnitureDamageEvent(mechanic, baseEntity, player, block);
                    Bukkit.getScheduler().runTask(instance, () -> {
                        Bukkit.getPluginManager().callEvent(event);
                    });
                    return event.isCancelled();
                }).get();
            } catch (Exception e) {
                return false;
            }
        } else return !CustomBlockManager.isHMCBlock(block);

        //} else if (/*MaterialSetTag.LEAVES.isTagged(type) && */leavesAPI.getBlockDataAt(block.getLocation()).blockDataSound() != null) { //HMCLeaves Mechanic
        //return false;
        //}
    }

    public long calculateTickPeriod(Player player, Block block, ItemStack tool) {

        String itemId = CustomBlockManager.getBlockId(block);
        AdvancedBlockData advancedBlockData = getAdvancedBlockData(itemId);
        if (advancedBlockData == null)
            return 60;

        Destroy destroy = advancedBlockData.getDestroy();
        Drop drop = advancedBlockData.getDrop();
        double hardness = advancedBlockData.getBlockHardness();
        if (drop == null) return 0;
        if (destroy == null) return 0;

        return calculateTickPeriod(player, tool, hardness, destroy, drop);
    }


    public long calculateTickPeriod(Player player, final ItemStack tool, final double hardness, final Destroy destroy, final Drop drop) {
        double speedMultiplier = 1;

        float defaultToolSpeed = destroy.getDefaultToolSpeed(tool);
        int efficiencyLevel = tool.getEnchantmentLevel(Enchantment.DIG_SPEED);
        if (destroy.isWhiteListItem(tool))
            defaultToolSpeed = 3.5F;

        if (destroy.canDestroy(tool)) {
            speedMultiplier = defaultToolSpeed;

            if (!drop.canDrop(tool))
                speedMultiplier = 1.0D;

            if (efficiencyLevel > 0)
                speedMultiplier += Math.pow(efficiencyLevel, 2.0D) + 1.0D;
        }

        if (player.hasPotionEffect(PotionEffectType.FAST_DIGGING)) {
            int hasteLevel = Objects.requireNonNull(player.getPotionEffect(PotionEffectType.FAST_DIGGING)).getAmplifier() + 1;
            speedMultiplier *= 0.2D * hasteLevel + 1.0D;
        }

        //if (player.isInWater() && !tool.containsEnchantment(Enchantment.WATER_WORKER))
        //    speedMultiplier /= 5.0D;

        //if (!player.isOnGround())
        //    speedMultiplier /= 5.0D;

        double damage = speedMultiplier / hardness;


        if (!destroy.isSolid()) {
            damage /= 30.0D;

        } else if (destroy.isSolid()) {
            if (destroy.isToolEnough(tool)) {
                if (destroy.isTypeEnough(tool)) {
                    damage /= 30.0D;
                } else {
                    damage /= 50.0D;
                }
            } else damage /= 100.0D;

        }
        if (damage > 1.0D)
            return 0L;

        return (long) Math.ceil(1.0D / damage);
    }
    
}

```

i made the breaker system almost 2 years ago and minecraft already added it before i made it available. that's sad. Lol anyway, if oraxen devs want to add it to previous versions, the system is exactly like that. i'm not going to open a PR, i have my own class methods, you just need to create a section called 'destroy' and if there's something you don't understand you can ask me. discord/bckd00r

**Comment by TuhkanenS** [comment]
It turns out that this bug will be fixed in 1.21 or 1.20.5?

**Comment by Boy0000** [comment]
> Instead of making a list of tools and checking for all those cases, you could use and edit NMS getDestroyProgress method and edit the iblockdata.getDestroySpeed method to get rid of the mining fatigue check I'm pretty sure

not really. getDestroySpeed is on the item, not the block
Cant really override getDestroySpeed either for an OraxenItem
Thats also not the core issue here

Core problem is to deal with speed of a custom block, which is only dictated by the hardness of the block
also "best tools" would also be factored in, otherwise it does the vanilla logic

**Comment by Boy0000** [comment]
superseeded by 2.0 implementation

**Pull request closed without merging**
