### PR TITLE
Fixed custom armors breaking too easily

### PR DESCRIPTION
**Pull request by Mowstyl**
After manually changing the durability of items with the durability mechanic, the event should be cancelled/set to 0.

### CODE REVIEW

**Comment by Boy0000** [comment]
Thanks for the PR 👍 for future ones please use another branch than master in your fork to mitigate potential conflicts
Feel free to rebase this onto "develop" otherwise ill do so before publishing 👍

**Comment by Mowstyl** [comment]
I'll rebase it as soon as possible. I didn't know about the develop branch.

**Comment by Boy0000** [comment]
No worries, heres a ["contribution guide"](https://github.com/oraxen/oraxen#contributing)

**Comment by Mowstyl** [comment]
By the way, I think this fixes the TODO on line 59 of the durability mechanic.
//TODO Figure out why when mending this sets the durability abit too high in the actual Damagable meta

**Comment by Mowstyl** [comment]
Sorry for writing too many messages, I'm not used to using github on mobile and I'm not on the computer.
I've been using my patch in my server for a while, no problems reported.

**Pull request merged**
