### PR TITLE
Allow upload pack using http and include extra folder into resource pack

### PR DESCRIPTION
**Pull request by yuxuanchiadm**
Allow upload pack using http and include extra folder into resource pack

### CODE REVIEW

**Comment by Boy0000** [comment]
@yuxuanchiadm Isn't this VirtualPack just the assets folder? Like `Oraxen/pack/assets/namespace/...` not much else you can include so not sure this is needed

**Comment by yuxuanchiadm** [comment]
Sometimes other plugins generate resources too. It will be nice if we can include them directly : )

**Comment by Boy0000** [comment]
I mean other plugins might generate stuff but you would still import this by adding it to `Oraxen/pack`
Unless you mean files are generated and added during runtime via API which might be abit scuffy, better to just copy paste but

**Comment by yuxuanchiadm** [comment]
If other plugins generate some assets. I want to automatically include them. Instead copy them manually. It will massively simplify test process

**Pull request closed without merging**
