### PR TITLE
add some more parentmodel options

### PR DESCRIPTION
**Pull request by Boy0000**

### CODE REVIEW

**Comment by Emibergo02** [comment]
is this related to #395?

**Comment by Boy0000** [comment]
no not currently, might include it but unable to reproduce it.

**Comment by Emibergo02** [comment]
> no not currently, might include it but unable to reproduce it.

https://github.com/oraxen/oraxen/issues/395#issuecomment-1229465350

**Comment by Th0rgal** [comment]
good idea

**Pull request merged**
