### PR TITLE
Support Folia Oraxen 1.X

### PR DESCRIPTION
**Pull request by Euphillya**
Update on the PR: https://github.com/oraxen/oraxen/pull/1271

I removed the support for Energy to implement Oraxen's own version in order to maintain it properly. I believe the changes can be easily included in this version 2.0.

I want to point out that I haven't been able to test the features for Folia yet. Normally, for Spigot, nothing should change.

### CODE REVIEW

**Comment by Boy0000** [comment]
unable to merge this PR into 1.X due to it removing 1.18->1.19 support
Consider making this only for 2.0 as any major changes arent coming to 1.X anymore either
and 2.0 drops 1.20.3 and below anyway

**Comment by Euphillya** [comment]
> unable to merge this PR into 1.X due to it removing 1.18->1.19 support Consider making this only for 2.0 as any major changes arent coming to 1.X anymore either and 2.0 drops 1.20.3 and below anyway

I know, I can't compile on my side, for that I put a Todo to put it back once the test is conclusive on Folia without breaking Spigot (That's why I still updated on the old versions).

**Comment by DarkyG2** [comment]
Issues:
- When breaking a furniture with a hitbox, the MSPT goes to shit and puts the server to 1 tps and I'm getting some error spams: https://pastebin.com/hhy6AJe0

- Getting this random error on join/leave/idle: https://pastebin.com/hqfrEzbg

- Minimessage isn't parsed correctly, I don't have **ANYTHING** in my configs containing this string shown in the error: https://pastebin.com/LH1Mc4Ts, you can refer to my issue here: https://github.com/oraxen/oraxen/pull/1271#issuecomment-2325081641

**Comment by DarkyG2** [comment]
On dyeable furnitures, if you break them they will lose their colors. Tested on a paper server with the default branch: 0 issues, on this branch on a folia server: issue

**Comment by Euphillya** [comment]
> On dyeable furnitures, if you break them they will lose their colors. Tested on a paper server with the default branch: 0 issues, on this branch on a folia server: issue

Can you show me a video to reproduce it?

**Comment by Euphillya** [comment]
I am stopping support on the PR.

**Pull request closed without merging**
