### PR TITLE
New features and improvements

### PR DESCRIPTION
**Pull request by Happy-FZM**
1. Improve isStandingInside checks (Use the correct collision box to determine whether the entity is standing at the target position of the block)
2. Support custom oraxen inventory icon display name

### CODE REVIEW

**Comment by Boy0000** [comment]
thanks for another PR 👍 
went ahead and further tweaked BlokcHelpers#isStandingInside to use BoundingBoxes for more accuracy
Also checking for players being in spectator, as invisible entities themselves should still count against placing there
per vanilla behaviour

**Comment by Happy-FZM** [comment]
> thanks for another PR 👍 went ahead and further tweaked BlokcHelpers#isStandingInside to use BoundingBoxes for more accuracy Also checking for players being in spectator, as invisible entities themselves should still count against placing there per vanilla behaviour

You should also exclude Item entity, so the type should be LivingEntity😄

**Comment by Happy-FZM** [comment]
> True though stuff like ArmorStand and such entities which arent LivingEntity should also count Might just exclude Item then, cant think of anything else

In fact, ArmorStand extends LivingEntity

**Comment by Boy0000** [comment]
Thanks, idk how i forgot that, pushed a commit to fix it ❤️

**Pull request merged**
